### ISSUE TITLE
install dir awareness

### ISSUE THREAD

**Issue by ThePotatoGuy** [Monika-After-Story/mas-installer#3]
I assume the installer currently is expecting the user to select the `game/` dir, correct? 
Can this determine if the user selected the `game/` dir vs the root dir and adjust the extract process as appropriate?

**Comment by Booplicate** [comment]
It's expecting the base directory (it prompts for a "Doki Doki Literature Club" directory). If the selected directory is invalid, it will tell it to the user (twice), but still install where asked in case that's what the user wants (usually installers allow that).

Currently there's no explicit handling to convert `.../DDLC/game/` into `.../DDLC/`, I could try to add that if needed.

**Comment by ThePotatoGuy** [comment]
well right now i tried it but it installed as if the root dir was game dir, so at the very least it needs to do current mod zip format or somehow know the difference.

**Comment by Booplicate** [comment]
Because it used the latest release which was packed to be installed into `game/`. The next releases should be packed to be installed into base dir.

**Comment by Booplicate** [comment]
@ThePotatoGuy we're also removing existing libs, so along with new package structure, we also need to include those.

**Comment by ThePotatoGuy** [comment]
we are changing build structure to include libs right? as you recommended we do?

i think we need to setup a test release to make sure everything works right. Can you make a way to change the update url easily for testing? I'll make a test release on my mas fork also probably a pr to update build

**Comment by Booplicate** [comment]
You should be able to locally change these lines
https://github.com/Monika-After-Story/mas-installer/blob/89fba975b29f5383d52c862f8d730e4c9967a3bb/src/main.rs#L22-L24
to your repo. Then build it using `cargo`. Assuming the release has correct name and structure, it should download and install it.

**Comment by Booplicate** [comment]
This seems to be resolved.
